#!/usr/bin/env bash
#Display numbers from 1 to 20
#the string "bad luck from china" in the 4th loop
#the string "bad luck from japan" in the 9th loop
#the string "bad luck from italy" in the 17th loop

i=1

while [ $i -le 20 ]; do
echo "$i"
case "$i" in
4)
echo "bad luck from China" ;;
9)
echo "bad luck from Japan" ;;
17)
echo "bad luck from Italy" ;;
esac
i=$((i+1))
done
